### ISSUE TITLE
multi tracking

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#70]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Voice-Recorder/issues) or [closed](https://github.com/FossifyOrg/Voice-Recorder/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Voice-Recorder/discussions) or [closed](https://github.com/FossifyOrg/Voice-Recorder/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Voice-Recorder/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

is it possible to have this work like a 4 (or more) track recorder where i can layer voice recordings on different lanes. you have all the technology to do this, youd just need to copy and paste ui elements and have a pop up telling the user to wear headphones to prevent audio bleeding into other tracks or muting the tracks while recording. youd also have to save the tracks separately and together which means collecting them all in a single folder.

### Why do you want this feature?

to record layered audios

**Comment by RustoMCSpit** [comment]
![17321891933648271668493728587178](https://github.com/user-attachments/assets/331ab1f7-aea9-48d3-9b04-35a9b8c38880)

**Comment by RustoMCSpit** [comment]
if this is done, id recommend allowing users to upload audio files for tracks from files or copy and paste

**Comment by RustoMCSpit** [comment]
@naveensingh if i make a donation, can this be prioritised?

**Comment by naveensingh** [comment]
Nope.

Whether this will be considered for implementation is yet to be decided anyway.

**Comment by RustoMCSpit** [comment]
also, making this compatible with dawproject would allow for immediare import into daws https://github.com/bitwig/dawproject

**Comment by HT-7** [comment]
It should at least support stereo audio (recording from both microphones).
**Optional** of course. Some phones might have issues with that.

**Comment by RustoMCSpit** [comment]
recording screen audio with software https://github.com/FossifyOrg/Voice-Recorder/issues/73 and external mic via hardware simutaneously should also happen

**Comment by RustoMCSpit** [comment]
> also, making this compatible with dawproject would allow for immediare import into daws https://github.com/bitwig/dawproject

hey apple, give me money for my idea you obviously ripped off lmao 🙄

**Comment by RustoMCSpit** [comment]
> Nope.
> 
> Whether this will be considered for implementation is yet to be decided anyway.

Who is in charge of considering it?

**Comment by naveensingh** [comment]
It helps to do some research before deciding whether to implement something, it's not based on a whim.

**Comment by naveensingh** [comment]
And no, this does not fit the bill. Use a DAW or something.

**Comment by RustoMCSpit** [comment]
if you change your mind, please look at Apple's IOS default voice memos app. theyve added this exact feature and it could be good reference.

**Comment by RustoMCSpit** [comment]
if i built this, would you merge a PR

**Comment by naveensingh** [comment]
> if i built this, would you merge a PR

I meant it doesn't fit with the app's goal (a keep-it-simple voice recorder app), issues won't be closed for a lack of time/resources.

> if you change your mind, please look at Apple's IOS default voice memos app

Sure :)

**Comment by RustoMCSpit** [comment]
> > if i built this, would you merge a PR
> 
> I meant it doesn't fit with the app's goal (a keep-it-simple voice recorder app), issues won't be closed for a lack of time/resources.

sorry for rhe incessant questions, if i made it a setting, or somehow had a very simple, easy to understand gui, would it then be merged or should i look at something else

**Comment by naveensingh** [comment]
> would it then be merged or should i look at something else

Unlikely. I would suggest you to look for alternatives, the feature does not make sense for now.
